// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYpcmF6g3zAH60DSYPU74JAAKBWdzzYM',
    appId: '1:108456209943:web:fe3d39a420b0e2f50df652',
    messagingSenderId: '108456209943',
    projectId: 'utility-notes-23eec',
    authDomain: 'utility-notes-23eec.firebaseapp.com',
    storageBucket: 'utility-notes-23eec.firebasestorage.app',
    measurementId: 'G-BR8JPK7TPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2rGWPEsEqWqk3iStJWApSSY7BvibgNSE',
    appId: '1:108456209943:android:636ebf4fca707e990df652',
    messagingSenderId: '108456209943',
    projectId: 'utility-notes-23eec',
    storageBucket: 'utility-notes-23eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzrAZC6darqQ7f_BUD-ned4ctPJUIJE4',
    appId: '1:770725387248:ios:346fb9e892efcce28fdb35',
    messagingSenderId: '770725387248',
    projectId: 'building-utility-system',
    storageBucket: 'building-utility-system.firebasestorage.app',
    iosBundleId: 'com.example.buildingUtilityManagementSystem',
  );
}
